### ISSUE TITLE
Question: data

### ISSUE THREAD

**Issue by kargaranamir** [mhndev/location-service#2]
Hi,
What is the best way to find data like [this](https://github.com/mhndev/location-service/blob/develop/.docker-compose/web-server/feed/locations/locations.json)?

**Comment by mhndev** [comment]
Hi Amir Hossein,
It's an old project and unfortunately I don't remember much.

**Comment by kargaranamir** [comment]
I really appreciate your response. 
What about this project (https://github.com/mhndev/iran-geography)? 
On the official Iran Statistics website, I didn't see anything about squares, intersections, etc. How do you get those?

**Comment by mhndev** [comment]
You're welcome.
Those information were given to me and it has been an excel file and I just
imported it into elasticsearch for searching.
and also I added Finglish names as well.

**Comment by kargaranamir** [comment]
Thank you so much for your answer.
